[2024-10-15T01:11:53.627+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T01:11:53.645+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asalex.write_asalex_to_file manual__2024-10-15T01:10:33.090372+00:00 [queued]>
[2024-10-15T01:11:53.654+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asalex.write_asalex_to_file manual__2024-10-15T01:10:33.090372+00:00 [queued]>
[2024-10-15T01:11:53.655+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-15T01:11:53.667+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): write_asalex_to_file> on 2024-10-15 01:10:33.090372+00:00
[2024-10-15T01:11:53.676+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'asalex', 'write_asalex_to_file', 'manual__2024-10-15T01:10:33.090372+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/asalex.py', '--cfg-path', '/tmp/tmp15mbjbfo']
[2024-10-15T01:11:53.678+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask write_asalex_to_file
[2024-10-15T01:11:53.673+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=216) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-15T01:11:53.678+0000] {standard_task_runner.py:72} INFO - Started process 218 to run task
[2024-10-15T01:11:53.729+0000] {task_command.py:467} INFO - Running <TaskInstance: asalex.write_asalex_to_file manual__2024-10-15T01:10:33.090372+00:00 [running]> on host 599ca003dbbf
[2024-10-15T01:11:53.811+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='asalex' AIRFLOW_CTX_TASK_ID='write_asalex_to_file' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T01:10:33.090372+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T01:10:33.090372+00:00'
[2024-10-15T01:11:53.812+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-15T01:11:53.813+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-15T01:11:53.813+0000] {logging_mixin.py:190} INFO - Current task name:write_asalex_to_file state:running start_date:2024-10-15 01:11:53.646248+00:00
[2024-10-15T01:11:53.813+0000] {logging_mixin.py:190} INFO - Dag name:asalex and current dag run status:running
[2024-10-15T01:11:53.813+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T01:11:53.822+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/asalex.py", line 24, in write_asalex_to_file
    f.write(f"Today, you will: {response['asalex']}\r\n")
                                ~~~~~~~~^^^^^^^^^^
KeyError: 'asalex'
[2024-10-15T01:11:53.831+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-15T01:11:53.831+0000] {logging_mixin.py:190} INFO - Task start:2024-10-15 01:11:53.646248+00:00 end:2024-10-15 01:11:53.831286+00:00 duration:0.185038
[2024-10-15T01:11:53.832+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): write_asalex_to_file> dag:<DAG: asalex> dagrun:<DagRun asalex @ 2024-10-15 01:10:33.090372+00:00: manual__2024-10-15T01:10:33.090372+00:00, state:running, queued_at: 2024-10-15 01:11:50.791816+00:00. externally triggered: True>
[2024-10-15T01:11:53.832+0000] {logging_mixin.py:190} INFO - Failure caused by 'asalex'
[2024-10-15T01:11:53.832+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=asalex, task_id=write_asalex_to_file, run_id=manual__2024-10-15T01:10:33.090372+00:00, execution_date=20241015T011033, start_date=20241015T011153, end_date=20241015T011153
[2024-10-15T01:11:53.845+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T01:11:53.845+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 38 for task write_asalex_to_file ('asalex'; 218)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/asalex.py", line 24, in write_asalex_to_file
    f.write(f"Today, you will: {response['asalex']}\r\n")
                                ~~~~~~~~^^^^^^^^^^
KeyError: 'asalex'
[2024-10-15T01:11:53.860+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-15T01:11:53.882+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T01:11:53.888+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
